// Auto-generated by scripts/optimize-media.mjs. Do not edit by hand.
const mediaManifest = {
  "ai-attack-manager-config": {
    "type": "image",
    "src": "/media/ai-attack-manager-config.webp",
    "width": 1204,
    "height": 280
  },
  "ai-attack-manager-data": {
    "type": "image",
    "src": "/media/ai-attack-manager-data.webp",
    "width": 1600,
    "height": 294
  },
  "ai-boss-data-asset": {
    "type": "image",
    "src": "/media/ai-boss-data-asset.webp",
    "width": 1600,
    "height": 604
  },
  "ai-boss-phase-1": {
    "type": "video",
    "src": "/media/ai-boss-phase-1.mp4",
    "poster": "/media/ai-boss-phase-1.jpg",
    "width": 720,
    "height": 290
  },
  "ai-boss-phase-2": {
    "type": "video",
    "src": "/media/ai-boss-phase-2.mp4",
    "poster": "/media/ai-boss-phase-2.jpg",
    "width": 720,
    "height": 406
  },
  "ai-boss-phase-transition": {
    "type": "video",
    "src": "/media/ai-boss-phase-transition.mp4",
    "poster": "/media/ai-boss-phase-transition.jpg",
    "width": 720,
    "height": 290
  },
  "ai-crowd-avoidance": {
    "type": "video",
    "src": "/media/ai-crowd-avoidance.mp4",
    "poster": "/media/ai-crowd-avoidance.jpg",
    "width": 720,
    "height": 294
  },
  "ai-idle-to-engage": {
    "type": "video",
    "src": "/media/ai-idle-to-engage.mp4",
    "poster": "/media/ai-idle-to-engage.jpg",
    "width": 720,
    "height": 290
  },
  "ai-patrol-loop": {
    "type": "video",
    "src": "/media/ai-patrol-loop.mp4",
    "poster": "/media/ai-patrol-loop.jpg",
    "width": 720,
    "height": 290
  },
  "ai-player-spotted": {
    "type": "video",
    "src": "/media/ai-player-spotted.mp4",
    "poster": "/media/ai-player-spotted.jpg",
    "width": 720,
    "height": 290
  },
  "ai-strafe-attack": {
    "type": "video",
    "src": "/media/ai-strafe-attack.mp4",
    "poster": "/media/ai-strafe-attack.jpg",
    "width": 720,
    "height": 290
  },
  "ai-vision-perception": {
    "type": "video",
    "src": "/media/ai-vision-perception.mp4",
    "poster": "/media/ai-vision-perception.jpg",
    "width": 720,
    "height": 290
  },
  "audio-boss-soundtrack-manager": {
    "type": "image",
    "src": "/media/audio-boss-soundtrack-manager.webp",
    "width": 915,
    "height": 192
  },
  "audio-dynamic-footstep": {
    "type": "image",
    "src": "/media/audio-dynamic-footstep.webp",
    "width": 1600,
    "height": 262
  },
  "case-study-hero": {
    "type": "image",
    "src": "/media/hero-background.webp",
    "width": 1600,
    "height": 632
  },
  "combat-camera-reset": {
    "type": "video",
    "src": "/media/combat-camera-reset.mp4",
    "poster": "/media/combat-camera-reset.jpg",
    "width": 720,
    "height": 290
  },
  "combat-damage-calc-ge": {
    "type": "image",
    "src": "/media/combat-damage-calc-ge.webp",
    "width": 1600,
    "height": 774
  },
  "combat-damage-hostile": {
    "type": "video",
    "src": "/media/combat-damage-hostile.mp4",
    "poster": "/media/combat-damage-hostile.jpg",
    "width": 720,
    "height": 290
  },
  "combat-damage-player": {
    "type": "video",
    "src": "/media/combat-damage-player.mp4",
    "poster": "/media/combat-damage-player.jpg",
    "width": 720,
    "height": 290
  },
  "combat-foot-ik": {
    "type": "video",
    "src": "/media/combat-foot-ik.mp4",
    "poster": "/media/combat-foot-ik.jpg",
    "width": 720,
    "height": 290
  },
  "combat-hit-reaction-unarmed": {
    "type": "video",
    "src": "/media/combat-hit-reaction-unarmed.mp4",
    "poster": "/media/combat-hit-reaction-unarmed.jpg",
    "width": 720,
    "height": 290
  },
  "combat-lock-on-death-switch": {
    "type": "video",
    "src": "/media/combat-lock-on-death-switch.mp4",
    "poster": "/media/combat-lock-on-death-switch.jpg",
    "width": 720,
    "height": 290
  },
  "combat-lock-on-switch": {
    "type": "video",
    "src": "/media/combat-lock-on-switch.mp4",
    "poster": "/media/combat-lock-on-switch.jpg",
    "width": 720,
    "height": 290
  },
  "combat-parry": {
    "type": "video",
    "src": "/media/combat-parry.mp4",
    "poster": "/media/combat-parry.jpg",
    "width": 720,
    "height": 290
  },
  "combat-players-stats": {
    "type": "image",
    "src": "/media/combat-players-stats.webp",
    "width": 814,
    "height": 386
  },
  "combat-state-heavy-weapon": {
    "type": "video",
    "src": "/media/combat-state-heavy-weapon.mp4",
    "poster": "/media/combat-state-heavy-weapon.jpg",
    "width": 720,
    "height": 290
  },
  "combat-state-light-weapon": {
    "type": "video",
    "src": "/media/combat-state-light-weapon.mp4",
    "poster": "/media/combat-state-light-weapon.jpg",
    "width": 720,
    "height": 290
  },
  "combat-state-unequipped": {
    "type": "video",
    "src": "/media/combat-state-unequipped.mp4",
    "poster": "/media/combat-state-unequipped.jpg",
    "width": 720,
    "height": 290
  },
  "combat-weapon-data": {
    "type": "image",
    "src": "/media/combat-weapon-data.webp",
    "width": 1600,
    "height": 496
  },
  "combat-weapons-stats": {
    "type": "image",
    "src": "/media/combat-weapons-stats.webp",
    "width": 804,
    "height": 134
  },
  "hero-background": {
    "type": "image",
    "src": "/media/hero-background.webp",
    "width": 1600,
    "height": 632
  },
  "interaction-inspect-note": {
    "type": "video",
    "src": "/media/interaction-inspect-note.mp4",
    "poster": "/media/interaction-inspect-note.jpg",
    "width": 720,
    "height": 290
  },
  "interaction-open-chest": {
    "type": "video",
    "src": "/media/interaction-open-chest.mp4",
    "poster": "/media/interaction-open-chest.jpg",
    "width": 720,
    "height": 290
  },
  "interaction-open-door": {
    "type": "video",
    "src": "/media/interaction-open-door.mp4",
    "poster": "/media/interaction-open-door.jpg",
    "width": 720,
    "height": 290
  },
  "interaction-open-locked-door": {
    "type": "video",
    "src": "/media/interaction-open-locked-door.mp4",
    "poster": "/media/interaction-open-locked-door.jpg",
    "width": 720,
    "height": 290
  },
  "interaction-pickup-heavy-weapon": {
    "type": "video",
    "src": "/media/interaction-pickup-heavy-weapon.mp4",
    "poster": "/media/interaction-pickup-heavy-weapon.jpg",
    "width": 720,
    "height": 290
  },
  "interaction-pickup-item": {
    "type": "video",
    "src": "/media/interaction-pickup-item.mp4",
    "poster": "/media/interaction-pickup-item.jpg",
    "width": 720,
    "height": 290
  },
  "inventory-action-context-menu": {
    "type": "video",
    "src": "/media/inventory-action-context-menu.mp4",
    "poster": "/media/inventory-action-context-menu.jpg",
    "width": 720,
    "height": 290
  },
  "inventory-category-showcase": {
    "type": "video",
    "src": "/media/inventory-category-showcase.mp4",
    "poster": "/media/inventory-category-showcase.jpg",
    "width": 720,
    "height": 290
  },
  "inventory-data-table-detail": {
    "type": "image",
    "src": "/media/inventory-data-table-detail.webp",
    "width": 1600,
    "height": 796
  },
  "inventory-data-table-summary": {
    "type": "image",
    "src": "/media/inventory-data-table-summary.webp",
    "width": 1600,
    "height": 170
  },
  "inventory-key-item-usage": {
    "type": "video",
    "src": "/media/inventory-key-item-usage.mp4",
    "poster": "/media/inventory-key-item-usage.jpg",
    "width": 720,
    "height": 290
  },
  "inventory-stack-overflow": {
    "type": "video",
    "src": "/media/inventory-stack-overflow.mp4",
    "poster": "/media/inventory-stack-overflow.jpg",
    "width": 720,
    "height": 290
  },
  "level-design-dungeon-environment-1": {
    "type": "image",
    "src": "/media/level-design-dungeon-environment-1.webp",
    "width": 1600,
    "height": 578
  },
  "level-design-dungeon-environment-2": {
    "type": "image",
    "src": "/media/level-design-dungeon-environment-2.webp",
    "width": 1600,
    "height": 578
  },
  "level-design-dungeon-environment-3": {
    "type": "image",
    "src": "/media/level-design-dungeon-environment-3.webp",
    "width": 1600,
    "height": 578
  },
  "level-design-first-floor-entrance": {
    "type": "image",
    "src": "/media/level-design-first-floor-entrance.webp",
    "width": 1600,
    "height": 632
  },
  "level-design-first-floor-idol-of-death": {
    "type": "image",
    "src": "/media/level-design-first-floor-idol-of-death.webp",
    "width": 1600,
    "height": 632
  },
  "level-design-first-floor-main-hall": {
    "type": "image",
    "src": "/media/level-design-first-floor-main-hall.webp",
    "width": 1600,
    "height": 632
  },
  "level-design-first-floor-second-entrance": {
    "type": "image",
    "src": "/media/level-design-first-floor-second-entrance.webp",
    "width": 1600,
    "height": 578
  },
  "level-design-first-floor-tunnel": {
    "type": "image",
    "src": "/media/level-design-first-floor-tunnel.webp",
    "width": 1600,
    "height": 578
  },
  "level-design-prison-section": {
    "type": "image",
    "src": "/media/level-design-prison-section.webp",
    "width": 1600,
    "height": 768
  },
  "level-design-second-floor-balcony": {
    "type": "image",
    "src": "/media/level-design-second-floor-balcony.webp",
    "width": 1600,
    "height": 632
  },
  "level-design-second-floor-entrance": {
    "type": "image",
    "src": "/media/level-design-second-floor-entrance.webp",
    "width": 1600,
    "height": 632
  },
  "level-design-third-floor-bridge": {
    "type": "image",
    "src": "/media/level-design-third-floor-bridge.webp",
    "width": 1600,
    "height": 578
  },
  "level-design-third-floor-chamber-entrance": {
    "type": "image",
    "src": "/media/level-design-third-floor-chamber-entrance.webp",
    "width": 1600,
    "height": 578
  },
  "level-design-third-floor-prayer-room": {
    "type": "image",
    "src": "/media/level-design-third-floor-prayer-room.webp",
    "width": 1600,
    "height": 578
  },
  "og-cover": {
    "type": "image",
    "src": "/media/og-cover.webp",
    "width": 1600,
    "height": 632,
    "jpg": "/media/og-cover.jpg"
  },
  "portrait": {
    "type": "image",
    "src": "/media/portrait.webp",
    "width": 400,
    "height": 400
  },
  "project-cover": {
    "type": "image",
    "src": "/media/hero-background.webp",
    "width": 1600,
    "height": 632
  }
}

export default mediaManifest
